main: jp.jyn.part10.Main
name: "${project.artifactId}"
version: "${project.version}"
website: "https://jyn.jp/bukkit-plugin-development-10/"
author: "@HimaJyun"

commands:
  part10:
    description: 'for Part10.'