main: jp.jyn.part4.Main
name: "${project.artifactId}"
version: "${project.version}"
website: "https://jyn.jp/bukkit-plugin-development-4/"
author: "@HimaJyun"

commands:
  hoge:
    description: 'This command can only be run by a player.'

permissions:
# プレイヤーのコマンド
  part4.player:
    default: true
# OP用のコマンド
  part4.op:
    default: op
# 上2つをまとめたもの
  part4.*
    children:
      part4.op: true
      part4.player: true