main: jp.jyn.part5.Main
name: "${project.artifactId}"
version: "${project.version}"
website: "https://jyn.jp/bukkit-plugin-development-5/"
author: "@HimaJyun"

commands:
  hoge:
    description: '"/hoge fuga" or "/hoge piyo"'